### ISSUE TITLE
Breaking Change[question|help wanted]: ImportError "cannot import name ARElement" after upgrading from 1.8.7 to 1.9.1

### ISSUE THREAD

**Issue by fyj2018** [melodypapa/py-armodel#353]
Hello,

I have developed a tool based on py-armodel. recently, my environment automatically upgraded the library from version `1.8.7` to `1.9.1`. Since the upgrade, my existing code fails to run due to ImportErrors.

It seems that several classes that were previously exposed in the top-level armodel package are no longer available there.

To Reproduce The following import statement worked perfectly in v1.8.7 but fails in v1.9.1:

```python
# This code causes an ImportError in v1.9.1
from armodel import (
    ARElement, 
    AsynchronousServerCallReturnsEvent, 
    BackgroundEvent, 
    BswBackgroundEvent, 
    BswDataReceivedEvent
)
```
Error Log

```txt
ImportError: cannot import name 'ARElement' from 'armodel' (c:\...\site-packages\armodel\__init__.py)
```
Questions

1.Is this a planned restructuring of the project (refactoring)?

2.Could you please advise on the correct import paths for ARElement and the Event classes in version 1.9.1?

3.Is there a migration guide or changelog available for these breaking changes?

For now, I have pinned my version to 1.8.7 to keep the tool running, but I would like to adapt to the latest version.

Thank you for your work on this library!

**Comment by fyj2018** [comment]
**Regression: Top-level exports removed in 1.9.1 refactor (ImportError)**
Hello,

I've identified the root cause of the ImportError in version 1.9.1. It stems from the changes in src/armodel/__init__.py.

The Change: In 1.8.7, you used wildcard imports which exposed all model classes at the top level:

```python
-from .models import *
```
In 1.9.1, this was replaced with explicit imports:
```python
+from armodel.models import AUTOSAR
```
LINK: https://github.com/melodypapa/py-armodel/commit/ebdd08b23933ac8f76306c27afecf0a5ef81b8d6#diff-5c9590fc479d250c3b5cd0db5c156169052f4c3ce114a8e665b18426cf644a16

<img width="1634" height="372" alt="Image" src="https://github.com/user-attachments/assets/cfcf701d-c69a-4db3-8d1c-e40c17a1d56d" />

The Impact: Commonly used classes like ARElement, AsynchronousServerCallReturnsEvent, BswBackgroundEvent, etc., are no longer accessible via from armodel import ....

While I understand the move towards explicit imports, this is a significant breaking change for existing scripts.

Suggestions:

Could you please restore the most commonly used classes (like ARElement and core Event types) to armodel/__init__.py?

Or, could you provide a "Migration Path" in the README/Changelog indicating where these classes have moved to? (e.g., armodel.models.M2...)

Thank you for the refactoring effort, it definitely makes the library structure cleaner, but a little backward compatibility for core classes would be very helpful!

**Comment by fyj2018** [comment]
Yup, that it works a few days,

**Comment by melodypapa** [comment]
I also work on the V2 version. I think about all the model classes will only export at armodel.models level later. @fyj2018
